- hosts: login:!builder # won't have a slurm control daemon when in build
  become: no
  gather_facts: false
  tasks:
    - name: Run sinfo
      shell: 'sinfo --noheader --format="%N %P %a %l %D %t" | sort' # using --format ensures we control whitespace: Partition,partition_state,max_jobtime,num_nodes,node_state,node_name
      register: sinfo
      changed_when: false
      until: sinfo.stdout_lines == expected_sinfo
      retries: 10
      delay: 5
      vars:
        expected_sinfo:
          - " extra up 60-00:00:00 0 n/a" # empty partition
          - "{{ openhpc_cluster_name }}-compute-[0-1] standard* up 60-00:00:00 2 idle"
