---

- name: Ensure templates directory exists
  file: 
    path: /etc/ansible-init/templates
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Inject templates
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/templates/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../resolv_conf/templates/resolv.conf.j2
    - ../../stackhpc.os-manila-mount/templates/ceph.conf.j2
    - ../../stackhpc.os-manila-mount/templates/ceph.keyring.j2
    - ../../stackhpc.openhpc/templates/gres.conf.j2

- name: Ensure files directory exists
  file: 
    path: /etc/ansible-init/files
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Inject files
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/files/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../resolv_conf/files/NetworkManager-dns-none.conf

- name: Ensure library directory exists
  file: 
    path: /etc/ansible-init/library
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Inject files
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/library/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../basic_users/library/terminate_user_sessions.py
    - ../../stackhpc.os-manila-mount/library/os_manila_share.py
    - ../../stackhpc.openhpc/library/sacct_cluster.py

- name: Ensure filter_plugins directory exists
  file: 
    path: /etc/ansible-init/filter_plugins
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Inject filter_plugins
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/filter_plugins/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../basic_users/filter_plugins/filter_keys.py
    - ../../stackhpc.openhpc/filter_plugins/slurm_conf.py

- name: Add filter_plugins ansible.cfg
  lineinfile:
    path: /etc/ansible-init/ansible.cfg
    line: "filter_plugins = /etc/ansible-init/filter_plugins"
    state: present
    owner: root
    group: root
    mode: 0644

- name: Ensure /exports/cluster directory exists
  file: 
    path: /exports/cluster
    state: directory
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ groups['control'] | first }}"

- name: Ensure /exports/cluster exists on control node
  ansible.builtin.file:
    path: /exports/cluster
    state: directory
    mode: '0755'
  delegate_to: "{{ groups['control'] | first }}"

- name: Copy manila share info to /exports/cluster
  copy:
    content: "{{ os_manila_mount_share_info | to_nice_yaml }}"
    dest: "/exports/cluster/manila_share_info.yml"
  delegate_to: "{{ groups['control'] | first }}"

- name: Write openhpc munge key
  copy:
    content: "{{ vault_openhpc_mungekey | b64decode }}"
    dest: "/exports/cluster/openhpc_munge.key"
    owner: munge
    group: munge
    mode: 0400
  delegate_to: "{{ groups['control'] | first }}"


- name: Inject compute initialisation playbook
  copy:
    src: compute-init.yml
    dest: /etc/ansible-init/playbooks/compute-init.yml
    owner: root
    group: root
    mode: 0644