---

- name: Ensure directories exist
  file: 
    path: "/etc/ansible-init/{{ item.directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - { directory: "templates" }
    - { directory: "files" }
    - { directory: "library" }
    - { directory: "filter_plugins" }

- name: Inject templates
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/templates/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../resolv_conf/templates/resolv.conf.j2
    - ../../stackhpc.os-manila-mount/templates/ceph.conf.j2
    - ../../stackhpc.os-manila-mount/templates/ceph.keyring.j2
    - ../../stackhpc.openhpc/templates/gres.conf.j2

- name: Inject files
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/files/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../resolv_conf/files/NetworkManager-dns-none.conf

- name: Inject files
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/library/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../basic_users/library/terminate_user_sessions.py
    - ../../stackhpc.os-manila-mount/library/os_manila_share.py
    - ../../stackhpc.openhpc/library/sacct_cluster.py

- name: Inject filter_plugins
  copy:
    src: '{{ item }}'
    dest: '/etc/ansible-init/filter_plugins/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - ../../basic_users/filter_plugins/filter_keys.py
    - ../../stackhpc.openhpc/filter_plugins/slurm_conf.py

- name: Add filter_plugins ansible.cfg
  lineinfile:
    path: /etc/ansible-init/ansible.cfg
    line: "filter_plugins = /etc/ansible-init/filter_plugins"
    state: present
    owner: root
    group: root
    mode: 0644

- name: Ensure nfs /exports/cluster configured
  block:
    - name: Ensure the /exports/hosts directory exists
      file:
        path: /exports/cluster
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy /etc/hosts to /exports/cluster
      copy:
        src: /etc/hosts
        dest: /exports/cluster/hosts
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: Copy manila share info to /exports/cluster
      copy:
        content: "{{ os_manila_mount_share_info | to_nice_yaml }}"
        dest: "/exports/cluster/manila_share_info.yml"
      when: os_manila_mount_share_info is defined

    - name: Write openhpc munge key
      copy:
        content: "{{ vault_openhpc_mungekey | b64decode }}"
        dest: "/exports/cluster/openhpc_munge.key"
        owner: munge
        group: munge
        mode: 0400
  delegate_to: "{{ groups['control'] | first }}"

- name: Inject compute initialisation playbook
  copy:
    src: compute-init.yml
    dest: /etc/ansible-init/playbooks/compute-init.yml
    owner: root
    group: root
    mode: 0644