---

- name: Compute node initialisation
  hosts: localhost
  become: yes
  vars:
    os_metadata: "{{ lookup('url', 'http://169.254.169.254/openstack/latest/meta_data.json') | from_json }}"
    server_node_ip: "{{ os_metadata.meta.k3s_server }}"
    compute_groups: "{{ os_metadata.meta.compute_groups | default([]) }}"

    # TODO: "role defaults"
    resolv_conf_nameservers: []

    # nfs_configurations:
    #   - nfs_export: "/exports/home"
    #     nfs_client_mnt_options:
    #     nfs_client_mnt_point: "/home"
    #     nfs_client_mnt_state: mounted
    #     nfs_server: "{{ server_node_ip }}"

    # os_manila_mount_state: mounted
    # os_manila_mount_opts:
    #   - x-systemd.device-timeout=30
    #   - x-systemd.mount-timeout=30
    #   - noatime
    #   - _netdev # prevents mount blocking early boot before networking available
    #   - rw
    # os_manila_mount_ceph_conf_path: /etc/ceph

    # basic_users_manage_homedir: false
    # basic_users_userdefaults:
    #   state: present
    #   create_home: "{{ basic_users_manage_homedir }}"
    #   generate_ssh_key: "{{ basic_users_manage_homedir }}"
    #   ssh_key_comment: "{{ item.name }}"
    # test_user_password: "zXpcWyGQL7jtZnqylQra4g=="
    # basic_users_users:
    #   - name: testuser # can't use rocky as $HOME isn't shared!
    #     password: "{{ test_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}" # idempotent
    #     uid: 1005
    # basic_users_groups: []

    # openhpc_conf_server: "{{ server_node_ip }}"

  tasks:
    - block:
        - name: Report skipping initialization if not compute node
          # meta: end_play produces no output
          debug:
            msg: "Skipping compute initialization as metadata compute_groups is empty"
        
        - meta: end_play
      when: compute_groups | length == 0 

    - name: Ensure the mount directory exists
      file:
        path: /mnt/cluster
        state: directory
        owner: root
        group: root
        mode: u=rwX,go= # is sensitive
    
    - name: Mount /mnt/cluster
      mount:
        path: /mnt/cluster
        src: "{{ server_node_ip }}:/exports/cluster"
        fstype: nfs
        opts: ro,sync
        state: mounted
      register: nfs_mount_result
      ignore_errors: true
      register: _mount_mnt_cluster
      # TODO: add some retries here?

    - block:
        - name: Report skipping initialization if cannot mount nfs
          # meta: end_play produces no output
          debug:
            msg: "Skipping compute initialization as cannot mount exports/cluster share"
        
        - meta: end_play
      when: _mount_mnt_cluster.failed
