- hosts: openondemand
  become: yes
  gather_facts: false
  tasks:
    - name: Delete ondemand files causing Trivy scan false-positives
      # Raised at https://github.com/OSC/ondemand/security/advisories/GHSA-f7j8-ppqm-m5vw
      # All declared not to be an issue by Open Ondemand as relevant packages not installed
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/opt/ood/ondemand/root/usr/share/gems/3.1/ondemand/{{ ondemand_package_version }}-1/gems/bootstrap_form-2.7.0/test/dummy/Gemfile.lock"
        - "/opt/ood/ondemand/root/usr/share/gems/3.1/ondemand/{{ ondemand_package_version }}-1/gems/bootstrap_form-4.5.0/demo/yarn.lock"
        - /var/www/ood/apps/sys/dashboard/node_modules/data-confirm-modal/Gemfile.lock

- hosts: builder
  become: yes
  tasks:
    - name: Revert ark repos
      ansible.builtin.include_role:
        name: release_train
        tasks_from: revert_repos.yml
      when: ansible_distribution_major_version == "9" #TODO update role once RL8 config decided
