
- hosts: extra_packages
  become: yes
  tags:
   - extra_packages
  tasks:
  - name: Install additional packages
    dnf:
      name: "{{ appliances_extra_packages }}"
    when: appliances_mode != 'configure' or appliances_packages_during_configure
